--
-- Civilezy EMS: Student CRM + Employee Management System
-- Tables: students, employees, attendance, leaves, daily_tasks
--

-- ============================================================
-- STUDENTS (Lead CRM)
-- ============================================================
create table public.students (
    id bigint generated by default as identity primary key,
    full_name text not null,
    phone text,
    email text,
    qualification text,          -- ITI, Diploma, BTech, Surveyor
    interested_course text,
    lead_source text,
    counselor_id bigint references public.sales(id) on delete set null,
    follow_up_date date,
    stage text not null default 'new-lead',
    notes text,
    index smallint default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create index on public.students (stage);
create index on public.students (counselor_id);

-- ============================================================
-- EMPLOYEES
-- ============================================================
create table public.employees (
    id bigint generated by default as identity primary key,
    name text not null,
    department text not null,    -- HR, IT Team, Digital Marketing Team, Content Creator Team
    role text,
    phone text,
    email text,
    joining_date date,
    salary bigint,
    status text not null default 'active',  -- active, inactive
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create index on public.employees (department);
create index on public.employees (status);

-- ============================================================
-- ATTENDANCE
-- ============================================================
create table public.attendance (
    id bigint generated by default as identity primary key,
    employee_id bigint not null references public.employees(id) on delete cascade,
    date date not null default current_date,
    check_in time,
    check_out time,
    working_hours numeric(4,2),
    status text not null default 'present',  -- present, absent, half-day, leave
    created_at timestamp with time zone not null default now(),
    unique (employee_id, date)
);

create index on public.attendance (employee_id);
create index on public.attendance (date);

-- ============================================================
-- LEAVES
-- ============================================================
create table public.leaves (
    id bigint generated by default as identity primary key,
    employee_id bigint not null references public.employees(id) on delete cascade,
    leave_type text not null,    -- annual, sick, casual, other
    reason text,
    start_date date not null,
    end_date date not null,
    status text not null default 'pending',  -- pending, approved, rejected
    admin_notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create index on public.leaves (employee_id);
create index on public.leaves (status);

-- ============================================================
-- DAILY TASKS
-- ============================================================
create table public.daily_tasks (
    id bigint generated by default as identity primary key,
    employee_id bigint not null references public.employees(id) on delete cascade,
    department text not null,
    task_title text not null,
    description text,
    submission_date date not null default current_date,
    status text not null default 'pending',  -- pending, under-review, completed
    admin_notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create index on public.daily_tasks (employee_id);
create index on public.daily_tasks (department);
create index on public.daily_tasks (submission_date);

-- ============================================================
-- UPDATED_AT TRIGGERS
-- ============================================================
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger students_updated_at before update on public.students
    for each row execute procedure public.set_updated_at();

create trigger employees_updated_at before update on public.employees
    for each row execute procedure public.set_updated_at();

create trigger leaves_updated_at before update on public.leaves
    for each row execute procedure public.set_updated_at();

create trigger daily_tasks_updated_at before update on public.daily_tasks
    for each row execute procedure public.set_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
alter table public.students enable row level security;
alter table public.employees enable row level security;
alter table public.attendance enable row level security;
alter table public.leaves enable row level security;
alter table public.daily_tasks enable row level security;

-- Students
create policy "Students select" on public.students for select to authenticated using (true);
create policy "Students insert" on public.students for insert to authenticated with check (true);
create policy "Students update" on public.students for update to authenticated using (true) with check (true);
create policy "Students delete" on public.students for delete to authenticated using (true);

-- Employees
create policy "Employees select" on public.employees for select to authenticated using (true);
create policy "Employees insert" on public.employees for insert to authenticated with check (true);
create policy "Employees update" on public.employees for update to authenticated using (true) with check (true);
create policy "Employees delete" on public.employees for delete to authenticated using (true);

-- Attendance
create policy "Attendance select" on public.attendance for select to authenticated using (true);
create policy "Attendance insert" on public.attendance for insert to authenticated with check (true);
create policy "Attendance update" on public.attendance for update to authenticated using (true) with check (true);
create policy "Attendance delete" on public.attendance for delete to authenticated using (true);

-- Leaves
create policy "Leaves select" on public.leaves for select to authenticated using (true);
create policy "Leaves insert" on public.leaves for insert to authenticated with check (true);
create policy "Leaves update" on public.leaves for update to authenticated using (true) with check (true);
create policy "Leaves delete" on public.leaves for delete to authenticated using (true);

-- Daily Tasks
create policy "DailyTasks select" on public.daily_tasks for select to authenticated using (true);
create policy "DailyTasks insert" on public.daily_tasks for insert to authenticated with check (true);
create policy "DailyTasks update" on public.daily_tasks for update to authenticated using (true) with check (true);
create policy "DailyTasks delete" on public.daily_tasks for delete to authenticated using (true);
